apiVersion: apps/v1
kind: Deployment
metadata:
  name: conductor-server
  namespace: netflix
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: conductor-server
  template:
    metadata:
      labels:
        io.kompose.service: conductor-server
    spec:
      containers:
        - env:
            - name: CONFIG_PROP
              value: config-postgres.properties
          image: anover/conductor:server
          imagePullPolicy: Always
          name: conductor-server
          ports:
            - containerPort: 8080
              hostPort: 8080