apiVersion: apps/v1
kind: Deployment
metadata:
  name: conductor-ui
  namespace: netflix
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: conductor-ui
  template:
    metadata:
      labels:
        io.kompose.service: conductor-ui
    spec:
      containers:
        - env:
            - name: WF_SERVER
              value: http://conductor-server:8080
          image: anover/conductor:ui
          imagePullPolicy: Always
          name: conductor-ui
          ports:
            - containerPort: 5000
              hostPort: 5004