elasticsearch:
  enabled: true
  #  imageTag: 7.16.3
  replicas: 1
  protocol: http
  fullnameOverride: "elasticsearch"
  clusterName: "elasticsearch"
  minimumMasterNodes: 1
  esConfig:
    elasticsearch.yml: |
      xpack.security.enabled: false
      xpack.security.transport.ssl.enabled: false
      xpack.security.transport.ssl.verification_mode: certificate
      xpack.security.transport.ssl.keystore.path: /usr/share/elasticsearch/config/certs/elastic-certificates.p12
      xpack.security.transport.ssl.truststore.path: /usr/share/elasticsearch/config/certs/elastic-certificates.p12
      xpack.security.http.ssl.enabled: false
      xpack.security.http.ssl.truststore.path: /usr/share/elasticsearch/config/certs/elastic-certificates.p12
      xpack.security.http.ssl.keystore.path: /usr/share/elasticsearch/config/certs/elastic-certificates.p12
  #  secretMounts:
  #    - name: elastic-certificates
  #      secretName: elastic-certificates
  #      path: /usr/share/elasticsearch/config/certs
  extraEnvs:
    - name: ES_JAVA_OPTS
      value: "-Xms512m -Xmx1024m"
  config:
    transport.host: 0.0.0.0
    discovery.type: single-node
    xpack.security.enabled: "false"
  healthCheckPath: /
  healthCheckPort: 9200
  persistence:
    enabled: true
#    existingClaim: esdata-conductor
#  extraEnvs:
#    - name: ELASTIC_PASSWORD
#      valueFrom:
#        secretKeyRef:
#          name: elastic-credentials
#          key: password

redis:
  enabled: true
  fullnameOverride: "redis"
  replica:
    replicaCount: 0
  usePassword: false

global:
  postgresql:
    auth:
      postgresPassword: "conductor"
      username: "conductor"
      password: "conductor"

postgresql:
  enabled: true
  fullnameOverride: "postgres"
  postgresUser: conductor
  postgresPassword: conductor
  persistence:
    enabled: true
  primary:
    initdb:
      scripts:
        setup.sql: |-
          CREATE DATABASE conductor;
          GRANT ALL PRIVILEGES ON `conductor`.* TO 'conductor';
          GRANT ALL ON *.* TO 'root'@'%';
#    existingClaim: pgdata-conductor

networks:
  internal: {}