apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: Kompose convert -c
    kompose.version: 1.30.0 (HEAD)
  creationTimestamp: null
  labels:
    io.kompose.service: conductor-server
  name: conductor-server
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: conductor-server
  strategy: {}
  template:
    metadata:
      annotations:
        kompose.cmd: Kompose convert -c
        kompose.version: 1.30.0 (HEAD)
      creationTimestamp: null
      labels:
        io.kompose.network/docker-internal: "true"
        io.kompose.service: conductor-server
    spec:
      containers:
        - env:
            - name: CONFIG_PROP
              value: config-local.properties
          image: conductor:server
          livenessProbe:
            exec:
              command:
                - curl
                - -I
                - -XGET
                - http://localhost:8080/health
            failureThreshold: 12
            periodSeconds: 60
            timeoutSeconds: 30
          name: conductor-server
          ports:
            - containerPort: 8080
              hostPort: 8080
              protocol: TCP
          resources: {}
      restartPolicy: Always
status: {}
